#!/usr/local/bin/python3

import os
import stat
import subprocess


def execute_command(command):
    try:
        result = subprocess.run(command, capture_output=True, text=True, check=True)
        print("Command Output:", result.stdout)
    except subprocess.CalledProcessError as e:
        print(f"Error Occurred: {e.stderr}")
    except FileNotFoundError:
        print("Command not found.")


# Run the function
execute_command(["ls", "-l"])

# Execute a simple command
result = subprocess.run(["touch", "oldfile.txt"], capture_output=True, text=True)

# Print the command output
print(result.stdout)  # Output: Hello, World!

# Execute a simple command
result = subprocess.run(["touch", "newfile.txt"], capture_output=True, text=True)

# Print the command output
print(result.stdout)  # Output: Hello, World!

# Execute a simple command
result = subprocess.run(["touch", "example.txt"], capture_output=True, text=True)

# Print the command output
print(result.stdout)  # Output: Hello, World!

# Open and read a file

with open('./dataFiles/myFile.txt', 'r') as file:
    content = file.read()
    print(content)

# Open and write to a file

# with open('./dataFiles/myFile.txt', 'w') as file:
# file.write("This is a new file.")

# Open and write to a file

with open('./dataFiles/myFile.txt', 'a') as file:
    file.write("\nAppending this line.")

# File related metadata:

file_path = "./dataFiles/myFile.txt"

# Get file size
print(f"File size: {os.path.getsize(file_path)} bytes")

# File stats

file_stats = os.stat("example.txt")
print(f"File size: {file_stats.st_size} bytes")
print(f"Last accessed: {file_stats.st_atime}")
print(f"Last modified: {file_stats.st_mtime}")
print(f"Creation time: {file_stats.st_ctime}")

# Check if file exists
print(f"File exists: {os.path.exists(file_path)}")

# Get absolute path
print(f"Absolute path: {os.path.abspath(file_path)}")

# Get file creation time
print(f"Creation time: {os.path.getctime(file_path)}")

# Get last modified time
print(f"Last modified: {os.path.getmtime(file_path)}")

# Directory related details:

directory = "."
files = os.listdir(directory)
print("Files in directory:", files)

for root, dirs, files in os.walk("."):
    print("Current Directory:", root)
    print("Subdirectories:", dirs)
    print("Files:", files)

# Create a file, directory and delete the directory:

with open("newfile.txt", "w") as file:
    file.write("Hello, world!")

os.mkdir("new_directory")

# Delete a file
os.remove("newfile.txt")

# Delete an empty directory
os.rmdir("new_directory")

# Rename a file or directory
os.rename("oldfile.txt", "newfile.txt")

# Change the chmod permission of the file:
# Make a file readable and writable
os.chmod("example.txt", stat.S_IRUSR | stat.S_IWUSR)

'''

import shutil

# Copy a file
shutil.copy("example.txt", "copy_example.txt")

# Move a file
shutil.move("example.txt", "new_directory/example.txt")


'''